/*
 * This file is generated by jOOQ.
 */
package com.code.rvlbank.entities.jooq;


import com.code.rvlbank.entities.jooq.tables.Account;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;
}
