/*
 * This file is generated by jOOQ.
 */
package com.code.rvlbank.entities.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = 595460100;

    private Long       id;
    private String     accountRef;
    private Boolean    locked;
    private BigDecimal balance;
    private String     currency;
    private Boolean    isActive;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.accountRef = value.accountRef;
        this.locked = value.locked;
        this.balance = value.balance;
        this.currency = value.currency;
        this.isActive = value.isActive;
    }

    public Account(
        Long       id,
        String     accountRef,
        Boolean    locked,
        BigDecimal balance,
        String     currency,
        Boolean    isActive
    ) {
        this.id = id;
        this.accountRef = accountRef;
        this.locked = locked;
        this.balance = balance;
        this.currency = currency;
        this.isActive = isActive;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountRef() {
        return this.accountRef;
    }

    public void setAccountRef(String accountRef) {
        this.accountRef = accountRef;
    }

    public Boolean getLocked() {
        return this.locked;
    }

    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Account other = (Account) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (accountRef == null) {
            if (other.accountRef != null)
                return false;
        }
        else if (!accountRef.equals(other.accountRef))
            return false;
        if (locked == null) {
            if (other.locked != null)
                return false;
        }
        else if (!locked.equals(other.locked))
            return false;
        if (balance == null) {
            if (other.balance != null)
                return false;
        }
        else if (!balance.equals(other.balance))
            return false;
        if (currency == null) {
            if (other.currency != null)
                return false;
        }
        else if (!currency.equals(other.currency))
            return false;
        if (isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.accountRef == null) ? 0 : this.accountRef.hashCode());
        result = prime * result + ((this.locked == null) ? 0 : this.locked.hashCode());
        result = prime * result + ((this.balance == null) ? 0 : this.balance.hashCode());
        result = prime * result + ((this.currency == null) ? 0 : this.currency.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(accountRef);
        sb.append(", ").append(locked);
        sb.append(", ").append(balance);
        sb.append(", ").append(currency);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
